### PR TITLE
Fixed Blackjack Command

### PR DESCRIPTION
**Pull request by RehanPlayz**

### CODE REVIEW

**Comment by RehanPlayz** [comment]
@V4NSH4J Also I'm getting some errors

**Comment by RehanPlayz** [comment]
```
ERRO[0325] await resume timed out for:                   cluster=default instance="Username#1234"

```

**Comment by V4NSH4J** [comment]
Hey, back when I updated Blackjack to work with buttons, I added manual AwaitResumes so that DankGrinder can do the whole blackjack game could be completed without sending any other command in between. That's probably messed up/ I used some wrong method for adding the AwaitResumes.

**Comment by RehanPlayz** [comment]
> Hey, back when I updated Blackjack to work with buttons, I added manual AwaitResumes so that DankGrinder can do the whole blackjack game could be completed without sending any other command in between. That's probably messed up/ I used some wrong method for adding the AwaitResumes.

oh ok

**Pull request closed without merging**
